<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
            [
                'id' => 2,
                'name' => 'access_role_permission',
                'group_name' => 'Role_Permission',
                'guard_name' => 'web',
            ],
            [
                'id' => 3,
                'name' => 'role_permission_create',
                'group_name' => 'Role_Permission',
                'guard_name' => 'web',
            ],
            [
                'id' => 4,
                'name' => 'role_permission_edit',
                'group_name' => 'Role_Permission',
                'guard_name' => 'web',
            ],
            [
                'id' => 5,
                'name' => 'role_permission_delete',
                'group_name' => 'Role_Permission',
                'guard_name' => 'web',
            ],
            [
                'id' => 6,
                'name' => 'access_to_setting',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 7,
                'name' => 'access_to_area',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 8,
                'name' => 'area_create',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 9,
                'name' => 'area_edit',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 10,
                'name' => 'area_delete',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 11,
                'name' => 'area_status',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 12,
                'name' => 'access_to_connection',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 13,
                'name' => 'connection_create',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 14,
                'name' => 'connection_edit',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 15,
                'name' => 'connection_delete',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 16,
                'name' => 'connection_status',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 17,
                'name' => 'access_to_package',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 18,
                'name' => 'package_create',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 19,
                'name' => 'package_edit',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 20,
                'name' => 'package_delete',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 21,
                'name' => 'package_status',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 22,
                'name' => 'access_to_idcard',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 23,
                'name' => 'idcard_create',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 24,
                'name' => 'idcard_edit',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 25,
                'name' => 'idcard_delete',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 26,
                'name' => 'idcard_status',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 27,
                'name' => 'access_to_device',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 28,
                'name' => 'device_create',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 29,
                'name' => 'device_edit',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 30,
                'name' => 'device_delete',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 31,
                'name' => 'device_status',
                'group_name' => 'Settings',
                'guard_name' => 'web',
            ],
            [
                'id' => 32,
                'name' => 'access_to_staff',
                'group_name' => 'Staff',
                'guard_name' => 'web',
            ],
            [
                'id' => 33,
                'name' => 'staff_create',
                'group_name' => 'Staff',
                'guard_name' => 'web',
            ],
            [
                'id' => 34,
                'name' => 'staff_edit',
                'group_name' => 'Staff',
                'guard_name' => 'web',
            ],
            [
                'id' => 35,
                'name' => 'staff_show',
                'group_name' => 'Staff',
                'guard_name' => 'web',
            ],
            [
                'id' => 36,
                'name' => 'staff_delete',
                'group_name' => 'Staff',
                'guard_name' => 'web',
            ],
            [
                'id' => 37,
                'name' => 'staff_status',
                'group_name' => 'Staff',
                'guard_name' => 'web',
            ],
            [
                'id' => 38,
                'name' => 'access_to_client',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 39,
                'name' => 'access_to_client_category',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 40,
                'name' => 'client_category_create',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 41,
                'name' => 'client_category_edit',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 42,
                'name' => 'client_category_delete',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 43,
                'name' => 'client_category_status',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 44,
                'name' => 'client_create',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 45,
                'name' => 'client_edit',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 46,
                'name' => 'client_show',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 47,
                'name' => 'client_delete',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 48,
                'name' => 'client_status',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 49,
                'name' => 'client_history',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 50,
                'name' => 'client_details',
                'group_name' => 'Client_Info',
                'guard_name' => 'web',
            ],
            [
                'id' => 51,
                'name' => 'access_to_bill',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 52,
                'name' => 'bill_list',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 53,
                'name' => 'client_bill_list',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 54,
                'name' => 'bill_invoice',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 55,
                'name' => 'bill_edit',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 56,
                'name' => 'bill_delete',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 57,
                'name' => 'bill_show',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 58,
                'name' => 'bill_pay',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 59,
                'name' => 'paid_client',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 60,
                'name' => 'unpaid_client',
                'group_name' => 'Bill',
                'guard_name' => 'web',
            ],
            [
                'id' => 61,
                'name' => 'access_to_complain',
                'group_name' => 'Complain',
                'guard_name' => 'web',
            ],
            [
                'id' => 62,
                'name' => 'classification_create',
                'group_name' => 'Complain',
                'guard_name' => 'web',
            ],
            [
                'id' => 63,
                'name' => 'classification_edit',
                'group_name' => 'Complain',
                'guard_name' => 'web',
            ],
            [
                'id' => 64,
                'name' => 'classification_delete',
                'group_name' => 'Complain',
                'guard_name' => 'web',
            ],
            [
                'id' => 65,
                'name' => 'classification_status',
                'group_name' => 'Complain',
                'guard_name' => 'web',
            ],
            [
                'id' => 66,
                'name' => 'complain_create',
                'group_name' => 'Complain',
                'guard_name' => 'web',
            ],
            [
                'id' => 67,
                'name' => 'complain_edit',
                'group_name' => 'Complain',
                'guard_name' => 'web',
            ],
            [
                'id' => 68,
                'name' => 'complain_delete',
                'group_name' => 'Complain',
                'guard_name' => 'web',
            ],
            [
                'id' => 69,
                'name' => 'complain_show',
                'group_name' => 'Complain',
                'guard_name' => 'web',
            ],
            [
                'id' => 70,
                'name' => 'request_for_area',
                'group_name' => 'Notification',
                'guard_name' => 'web',
            ],
            [
                'id' => 71,
                'name' => 'request_for_package',
                'group_name' => 'Notification',
                'guard_name' => 'web',
            ],
            [
                'id' => 72,
                'name' => 'request_for_connection',
                'group_name' => 'Notification',
                'guard_name' => 'web',
            ],
            [
                'id' => 73,
                'name' => 'request_for_bill_pay',
                'group_name' => 'Notification',
                'guard_name' => 'web',
            ],
            [
                'id' => 74,
                'name' => 'access_to_bank',
                'group_name' => 'Bank',
                'guard_name' => 'web',
            ],
            [
                'id' => 75,
                'name' => 'bank_create',
                'group_name' => 'Bank',
                'guard_name' => 'web',
            ],
            [
                'id' => 76,
                'name' => 'bank_edit',
                'group_name' => 'Bank',
                'guard_name' => 'web',
            ],
            [
                'id' => 77,
                'name' => 'bank_delete',
                'group_name' => 'Bank',
                'guard_name' => 'web',
            ],
            [
                'id' => 78,
                'name' => 'bank_status',
                'group_name' => 'Bank',
                'guard_name' => 'web',
            ],
            [
                'id' => 79,
                'name' => 'access_to_account',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 80,
                'name' => 'account_type_create',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 81,
                'name' => 'account_type_edit',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 82,
                'name' => 'account_type_delete',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 83,
                'name' => 'account_type_status',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 84,
                'name' => 'account_create',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 85,
                'name' => 'account_edit',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 86,
                'name' => 'account_show',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 87,
                'name' => 'account_delete',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 88,
                'name' => 'account_status',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 89,
                'name' => 'access_to_deposit_withdraw',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 90,
                'name' => 'deposit_withdraw_create',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 91,
                'name' => 'deposit_withdraw_edit',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 92,
                'name' => 'deposit_withdraw_delete',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 93,
                'name' => 'deposit_withdraw_show',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 94,
                'name' => 'balance_sheet',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 95,
                'name' => 'account_statement',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 96,
                'name' => 'access_to_expense_category',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 97,
                'name' => 'expense_category_create',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 98,
                'name' => 'expense_category_edit',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 100,
                'name' => 'expense_category_delete',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 101,
                'name' => 'expense_category_status',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 102,
                'name' => 'access_to_expense',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 103,
                'name' => 'expense_create',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 104,
                'name' => 'expense_edit',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 105,
                'name' => 'expense_delete',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 106,
                'name' => 'expense_show',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 107,
                'name' => 'access_to_balance_transfer',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 108,
                'name' => 'balance_transfer_create',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 109,
                'name' => 'balance_transfer_edit',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 110,
                'name' => 'balance_transfer_delete',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],

            [
                'id' => 111,
                'name' => 'balance_transfer_show',
                'group_name' => 'Account',
                'guard_name' => 'web',
            ],
            [
                'id' => 112,
                'name' => 'access_to_report',
                'group_name' => 'Report',
                'guard_name' => 'web',
            ],
            [
                'id' => 113,
                'name' => 'client_report',
                'group_name' => 'Report',
                'guard_name' => 'web',
            ],
            [
                'id' => 114,
                'name' => 'area_report',
                'group_name' => 'Report',
                'guard_name' => 'web',
            ],
            [
                'id' => 115,
                'name' => 'connection_report',
                'group_name' => 'Report',
                'guard_name' => 'web',
            ],
            [
                'id' => 116,
                'name' => 'package_report',
                'group_name' => 'Report',
                'guard_name' => 'web',
            ],
            [
                'id' => 117,
                'name' => 'device_report',
                'group_name' => 'Report',
                'guard_name' => 'web',
            ],
            [
                'id' => 118,
                'name' => 'client_category_report',
                'group_name' => 'Report',
                'guard_name' => 'web',
            ],
            [
                'id' => 119,
                'name' => 'admin_dashboard',
                'group_name' => 'Role_Permission',
                'guard_name' => 'web',
            ],

        ]);

    }
}
